# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bitcoin.proto for package 'bitcoin'

require 'grpc'
require 'bitcoin_pb'

module Bitcoin
  module BitcoinService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'bitcoin.BitcoinService'

      rpc :get_bitcoin, BitcoinRequest, BitcoinResponse
    end

    Stub = Service.rpc_stub_class
  end
end
